# Generated by Django 4.1.7 on 2023-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.IntegerField(max_length=100)),
                ('motdepasse', models.CharField(max_length=100)),
                ('datenaiss', models.DateField(max_length=100)),
            ],
        ),
    ]
