# Generated by Django 4.1.7 on 2023-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0002_alter_user_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='terre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.IntegerField()),
                ('Humidite', models.CharField(max_length=100)),
                ('Humiditesol', models.CharField(max_length=100)),
                ('forcedevent', models.IntegerField()),
                ('Rayonnementsolaire', models.CharField(max_length=100)),
                ('arrosage', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
