# Generated by Django 4.1.7 on 2023-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tel',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
