# Generated by Django 4.1.7 on 2023-04-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0005_rename_address_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
