# Generated by Django 4.1.7 on 2023-04-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0010_terrain_delete_terre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('Temperature', models.IntegerField()),
                ('humidite', models.FloatField()),
                ('HS', models.FloatField()),
                ('FV', models.IntegerField()),
                ('RS', models.IntegerField()),
                ('nterrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_irr.terrain')),
            ],
        ),
    ]
