# Generated by Django 4.1.7 on 2023-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0012_statistique_nuser_alter_terrain_proprietaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistique',
            old_name='nterrain',
            new_name='Nterrain',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='nuser',
        ),
        migrations.AddField(
            model_name='statistique',
            name='debit',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='RS',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='statistique',
            name='temperature',
            field=models.FloatField(default=10),
        ),
    ]
