# Generated by Django 4.1.7 on 2023-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0013_rename_nterrain_statistique_nterrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistique',
            name='consommation_eau',
            field=models.FloatField(default=100),
        ),
    ]
