# Generated by Django 4.1.7 on 2023-05-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0014_statistique_consommation_eau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='adresse',
        ),
    ]
