# Generated by Django 4.1.7 on 2023-05-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0015_remove_terrain_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=2)),
                ('quartier', models.CharField(max_length=200)),
                ('voie', models.CharField(max_length=200)),
                ('code_postale', models.IntegerField(default=150)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='terrain',
            name='id_adresse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_irr.adresse'),
        ),
    ]
