# Generated by Django 4.1.7 on 2023-05-01 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_irr', '0016_adresse_terrain_id_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire_terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(default='Male', max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_irr.terrain')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
