# Generated by Django 4.1.7 on 2023-05-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0019_remove_proprietaire_terrain_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire_terrain',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_irr.terrain'),
        ),
    ]
