# Generated by Django 4.1.7 on 2023-05-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0020_proprietaire_terrain_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='prop',
        ),
    ]
