# Generated by Django 4.1.7 on 2023-05-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0022_alter_proprietaire_terrain_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='fk_prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_irr.proprietaire_terrain'),
        ),
    ]
