# Generated by Django 4.1.7 on 2023-05-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0023_terrain_fk_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='gender',
        ),
    ]
