# Generated by Django 4.1.7 on 2023-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irr', '0024_remove_proprietaire_terrain_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire_terrain',
            old_name='firstname',
            new_name='cin',
        ),
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='proprietaire_terrain',
            name='user',
        ),
        migrations.AddField(
            model_name='proprietaire_terrain',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire_terrain',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire_terrain',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire_terrain',
            name='tel',
            field=models.IntegerField(default=144),
        ),
    ]
